import type { NextPage } from 'next';
import Head from 'next/head';

import { Terminal } from '../components/Terminal';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative h-screen w-screen flex justify-center items-center bg-black">
        <Terminal />
      </div>
    </div>
  );
};

export default Home;
